// <auto-generated />
namespace ECommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ghaith_s : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ghaith_s));
        
        string IMigrationMetadata.Id
        {
            get { return "202105202023483_ghaith_s"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
