// <auto-generated />
namespace ECommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DB_LO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_LO));
        
        string IMigrationMetadata.Id
        {
            get { return "202105150943125_DB_LO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
